# docker-compose.yaml
version: '3.1'

services:
  mariadb:
    container_name: team4-order-db
    image: mariadb:11.3.2
    restart: always
    # 환경에 따라 변경
    expose:
      - "3306"
    volumes:
      # DB 데이터 저장 디렉터리
      - ./data:/var/lib/mysql
      # 설정 파일 저장될 위치
      - ./config:/etc/mysql/conf.d
    environment:
      # 정의하지 않으면 실행 시, 에러가 발생합니다.
      - MYSQL_ROOT_PASSWORD=1234
      # 컨테이너 내의 시스템 타임존을 우리나라에 맞게 설정합니다.
      - TZ=Asia/Seoul
    command:
      # 위 명령어를 사용하지 않으면, 일부 설정이 latin으로 설정됩니다.
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
